apiVersion: v1
kind: Pod
metadata:
  labels:
    app: spring-boot
spec:
  containers:
  - name: maven
    image: maven:3.6.3-openjdk-14
    command:
    - cat
    tty: true
  - name: docker
    image: docker:test-git
    command:
    - cat
    tty: true